name: Format and Test

on:
  push:
    branches: [main, test]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-A warnings"
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Protocol Buffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Check formatting
        run: cargo fmt --check

      - name: Run unit tests
        run: cargo test
