name: Format and Test

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Check formatting
        run: cargo fmt --check

      - name: Run unit tests
        run: cargo test
