name: Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true

      - name: Build ubgpd Docker image
        run: docker build -t ubgp -f tests/integration/Dockerfile.ubgp .

      - name: Start test topology
        run: |
          docker compose -f tests/integration/docker-compose.yml up -d
          sleep 10

      - name: Check BGP neighbors status
        run: |
          echo "=== BGP Neighbors Status ==="
          docker exec integration-ubgp-1 ubgpc --server 127.0.0.1 neighbors
          docker exec integration_frr_1 vtysh -c "show bgp summary"
          docker exec integration_gobgp_1 vtysh -c "gobgp neighbor"
          
      - name: Check RIB contents
        run: |
          echo "=== IPv4 RIBs ==="
          docker exec integration-ubgp-1 ubgpc --server 127.0.0.1 rib -a 1 -s 1
          docker exec integration_frr_1 vtysh -c "show bgp ipv4"
          docker exec integration_gobgp_1 gobgp global rib -a ipv4
          echo "=== IPv6 RIBs ==="
          docker exec integration-ubgp-1 ubgpc --server 127.0.0.1 rib -a 2 -s 1
          docker exec integration_frr_1 vtysh -c "show bgp ipv6"
          docker exec integration_gobgp_1 gobgp global rib -a ipv6

      - name: Collect logs on failure
        if: failure()
        run: |
          echo "=== Container Status ==="
          docker ps -a
          echo "=== ubgp logs ==="
          docker exec integration-ubgp-1
          echo "=== gobgp logs ==="
          docker exec integration-gobgp-1
          echo "=== frr logs ==="
          docker exec integration-frr-1
          echo "=== BGP Neighbors ==="
          docker exec integration-ubgp-1 ubgpc --server 127.0.0.1 neighbors || true
